Track loot sent directly to the bank from Lunar Chests
MosheBenZacharia/GP-Per-Hour pull request #40
Opened 2024-04-30 13:23 UTC by BR-

In the meantime before the delta refactor mentioned in #38 is completed, this patch adds tracking for the "bank-all" button on the Moons of Peril reward chest. Could be set up for ToA loot and more, but I haven't done those, so I don't know the widget IDs. @daltonpearson might be able to get them.

(Loot Tracker)[https://github.com/runelite/runelite/blob/1a2913141c25290cd6b28d06f93fa7ede2c26e10/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java#L822] was the main reference I used for this, but to avoid double-counting if you send to your inventory, I needed to trigger off of the bank button instead of the popup window.

2024-05-01 12:13 UTC, MosheBenZacharia requested changes
Just did a quick pass, it seems like this will not render in the ledger / session panel, is that right? If that's the case it might be better to have a function inside TripData that gets itemQtys and bankedItemQtys combined that is used by the ledger / session panel to render these items.

I also left a comment about adding some other InterfaceIDs, seems pretty straightforward to just add all the ones Runelite tracks since we're going down this route :)

2024-05-01 12:13 UTC, MosheBenZacharia commented on src/main/java/com/gpperhour/GPPerHourPlugin.java
> +	private ItemContainer rewardsItemContainer;
probably no point in adding this as a field if we only reference it right after we assign it

2024-05-01 17:16 UTC, BR- commented
Thanks for the review.

The items do show in the side panel, but I don't know what the ledgers are, so I might have missed something. In `updatePluginState`, `itemQtys` is cleared and refilled with `getInventoryTotal`, `getEquipmentTotal`, and now also `getRewardsTotal` each tick, and `itemQtys` is then used to fill the session object / side panel.

The interface change looks great, I didn't know of `WidgetUtil`. Now we just need a mapping from `InterfaceID` to `InventoryID` for each reward chest, which should be pretty straightforward.

`rewardsItemContainer` is there just because the inventory/equipment ItemContainers are also there. When I started working on this I just looked everywhere inventory was mentioned, and made a duplicate for rewards. Happy to make it a local.

2024-05-02 01:38 UTC, MosheBenZacharia commented
> Thanks for the review.
> 
> The items do show in the side panel, but I don't know what the ledgers are, so I might have missed something. In `updatePluginState`, `itemQtys` is cleared and and then refilled using `getInventoryTotal`, `getEquipmentTotal`, and now also `getRewardsTotal`. Then, `itemQtys` is used to fill the session object / side panel.

Ok sweet, that sounds great. I didn't actually have time to test it and I haven't looked at this code in a while but that makes sense. The 'ledger' is the list that shows up when you hover over the gp/hr overlay that shows up on top of the inventory.

> 
> The interface change looks great, I didn't know of `WidgetUtil`. Now we just need a mapping from `InterfaceID` to `InventoryID` for each reward chest, which should be pretty straightforward.

Yep, that makes sense. Seems like there are already a few useful ones in InventoryID.java (COX, ToB, TOA).

> 
> `rewardsItemContainer` is there just because the inventory/equipment ItemContainers are also there. When I started working on this I just looked everywhere inventory was mentioned, and made a duplicate for rewards. Happy to make it a local.

Ok sweet, probably makes more sense to have it local.

2024-05-02 17:34 UTC, daltonpearson commented
ToA updates:
menuOptionClicked.param1() returns `50528260` for bank all.
the interface ID for the chest is: `771`

```
MenuOptionClicked(getParam0=-1, getParam1=50528260, getMenuOption=Bank-all, getMenuTarget=, getMenuAction=CC_OP_LOW_PRIORITY, getId=6)
WidgetUtil.componentToInterface(event.getParam1()): 771
```

2024-05-05 02:34 UTC, BR- commented
From the list supported by Loot Tracker, I've added all but Barrows (which, as far as I know, doesn't let you send items to your bank). I've only tested Fishing Trawler, Lunar Chests, and Managing Miscellania.

2024-05-05 02:47 UTC, MosheBenZacharia approved these changes
Looks great, thanks so much for working on this (both of you)!!

Let me know if you think it's ready to be merged.

2024-06-07 19:15 UTC, BR- commented
Sorry for the delay - I haven't been playing much, and haven't done specifically the content this fixes.
It does work in the places I have tested (Lunar, Trawler, Miscellania), so it's probably ready.
Untested: ToA, ToB, CoX, Colosseum, Drift Net Fishing, Wilderness Loot

2024-06-10 13:22 UTC, MosheBenZacharia commented
ok sweet, I'll just get this merged

2024-06-10 13:22 UTC, merged